# Generated by Django 3.1.1 on 2020-10-19 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.fileSystem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('EmailId', models.EmailField(max_length=128, unique=True)),
                ('FullName', models.TextField(max_length=200)),
                ('MobileNumber', models.TextField(max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('auth_change_failures', models.IntegerField(default=0)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountName', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FriendlyName', models.TextField(max_length=200)),
                ('SignPage', models.IntegerField(default=1)),
                ('SignPosition', models.CharField(choices=[('TL', 'TopLeft'), ('TR', 'TopRight'), ('BL', 'BottomLeft'), ('BR', 'BottomRight')], default='BR', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisText', models.TextField(max_length=500)),
                ('Sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersigntext', to='mainapp.usersign')),
                ('User', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSignImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VisImage', models.ImageField(upload_to='signature/')),
                ('Sign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersignimage', to='mainapp.usersign')),
                ('User', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_owner', models.BooleanField(default=False)),
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to=mainapp.fileSystem.models.user_directory_path)),
                ('IsSigned', models.BooleanField(default=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.account')),
                ('User', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
